### ISSUE TITLE
Setting a variable to a value in an array 

### ISSUE THREAD

**Issue by jchud13** [jbr/sibilant#106]
Hello! 

Quick question, I am having trouble figuring out the syntax. I am looking to do something like
`var count = seen[input];`

I have tried things like 

`(var count seen input)
(set count seen input)
(assign count [seen input]`

but obviously none of that works. Any guidance would be appreciated!

**Comment by whacked** [comment]
```sibilant
(var seen {"good" 1 "bad" 2})
(var input "good")
(var count (get seen input))
```

generates
```javascript
var seen = {
  "good": 1,
  "bad": 2
};
var input = "good";
var count = seen[input];
```

there's an interactive transpiler on https://docs.sibilant.org/ which is very helpful

**Comment by jchud13** [comment]
Thank you very much!
