### ISSUE TITLE
make sibilant-mode an independent repo and put it on melpa

### ISSUE THREAD

**Issue by mpenet** [jbr/sibilant#43]
Hello, 

This would allow for submodules based packaging in emacs without having to pull the whole sibilant source, while not really causing any changes on the "root" project. 

Also do you have any plan or ongoing work on porting sibilant to the latest node (and also continue to work on this project)? I am not able to compile or install it on v0.6.7 atm, maybe some indication in the README about the required versions of nodes would help new comers.

**Comment by mattly** [comment]
Also, if the emacs mode were in a separate repository it could be published on MELPA.

**Comment by mattly** [comment]
@jbr I'd be more than happy to help you get this setup sometime over lunch or at Dapper and Wise. Spacemacs keeps changing how they let you include non-melpa packages and it's kinda a pain.

**Comment by jbr** [comment]
https://github.com/milkypostman/melpa/pull/3305
https://github.com/jbr/sibilant-mode

**Comment by jbr** [comment]
I think I'm going to skip the submodule, unless someone has a compelling reason this should be in the sibilant repo

**Comment by mattly** [comment]
woo!

I don't see a need for the submodule, but a link in the readme would be a good idea.

**Comment by jbr** [comment]
https://melpa.org/#/sibilant-mode

M-x package-list-packages
C-s sibilant
i x
